### ISSUE TITLE
Android READ_SMS permissions clarification

### ISSUE THREAD

**Issue by kfiroo** [tkporter/react-native-sms#9]
Hey @tkporter, thanks for the great package :)
Just wondering why we need to request `PermissionsAndroid.PERMISSIONS.READ_SMS` permission?
Also, we don't currently use the M Permission model in our android app, is it possible to declare this permission in the manifest instead of requesting it on `send`?

**Comment by tkporter** [comment]
Hi! If I recall correctly, READ_SMS was required in order to get proper callbacks (completed/cancelled/error). One of the main reasons for this package was so we could get accurate information on the results of the SMS so we could get better information on our application.

Permissions can definitely be scary to a user-- if getting callbacks are not necessarily a priority then it could be worth removing a few lines that require READ_SMS.

Although it has been a while and I'm not too sure if I'm correct with the reasoning for READ_SMS, so you might want to take a few minutes and test what happens if you take out the permission.

As far as the call inside the `index.js`, that was an addition to RN at the time that gave support for non-Manifest permissions that were requested at runtime. It's perfectly acceptable to declare the permission in the Manifest as well.

Hope I was able to clarify some questions! I haven't meddled with the Android part of this in a good while so if you do see some room for improvement feel free to send in a PR :)

**Comment by kfiroo** [comment]
Thanks @tkporter, that makes sense :)

I think I'll end up using the `sms:` schema as I don't really need the callback at the moment.
